/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import org.apache.commons.lang3.StringUtils;
import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.CommandLineParser;
import org.apache.commons.cli.DefaultParser;
import org.apache.commons.cli.Options;
import org.apache.commons.cli.ParseException;

import java.util.Arrays;

public class App {
    static public String capMsg(String input) {
        return StringUtils.capitalize(input);
    }

    public static void main(String[] args) {
        String message = "";
        if(args.length != 0){
             message = args[0];
        }
        else{
            message = "no message input";
        }
        //test
        System.out.println("Old Message: " + message);
        System.out.println("New Message: " +  capMsg(message));
    }
}
